export const PRODUCT_CATEGORIES = [
  "Electronics",
  "Clothing & Apparel",
  "Food & Beverages",
  "Home & Garden",
  "Health & Beauty",
  "Sports & Outdoors",
  "Toys & Games",
  "Automotive",
  "Books & Media",
  "Industrial & B2B",
  "Office Supplies",
  "Pet Supplies",
  "Jewelry & Accessories",
  "Art & Crafts",
  "Other",
];

export const SUSTAINABILITY_FILTERS = [
  "Eco-Friendly Materials",
  "Recyclable Packaging",
  "Energy Efficient",
  "Organic / Natural",
  "Fair Trade Certified",
  "Low Carbon Footprint",
  "Biodegradable",
  "Cruelty Free",
  "Locally Sourced",
  "Vegan",
  "Upcycled / Recycled Content",
  "Water Efficient",
  "Renewable Energy Used in Production",
  "Long Lifespan / Durable",
  "None",
];
